import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/redux/provider/Provider";
import { ReactNode } from "react";
import Navigation from "./layout/navigation/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
