import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./layout/navigation/Navigation";
import { Providers } from "@/redux/provider/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
